name: Python Script Workflow
on: [push]
jobs:
    run-python-script:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'

            - name: Run Script
              run: python3 tddproject/automation/display.py    