name: Trigger PR From main_3_2 To main_3_2_deployment On Version To Main Merge & Create Release

on: 
  pull_request:
    types:
      - closed
    branches: [ main_django_3_2 ]

jobs:

  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install requests
        pip install pandas
        pip install tabulate
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Trigger PR to main_3_2_deployment & Create Release
      env:
        GITHUB_PAT: ${{ secrets.AUTOMATION_PAT }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PULL_NUMBER: ${{ github.event.number }}
        BRANCH_NAME: ${{ github.base_ref }}
        PR_USER: ${{ github.actor }}
        OWNER: ${{ github.repository_owner }}
        HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

      run: cd .github/workflows/Code; python3 create_release_pr.py